package com.joses.mali

import android.graphics.*
import android.graphics.pdf.PdfDocument
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

class PastTenantPdfGeneratorImpl {
    fun generatePdf(filePath: String) {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(500, 700, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas
        val paint = Paint()

        // 🔹 Title
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textSize = 18f
        paint.color = Color.BLACK
        canvas.drawText("Past Tenants Report", 150f, 40f, paint)

        // 🔹 Subtitle (Current Date)
        paint.textSize = 12f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
        val currentDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date())
        canvas.drawText("Generated on: $currentDate", 150f, 70f, paint)

        // 🔹 Table Headers Background
        paint.color = Color.LTGRAY
        canvas.drawRect(30f, 100f, 470f, 130f, paint)

        // 🔹 Table Headers
        paint.color = Color.BLACK
        paint.textSize = 12f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Name", 40f, 120f, paint)
        canvas.drawText("Move-in", 140f, 120f, paint)
        canvas.drawText("Move-out", 220f, 120f, paint)
        canvas.drawText("Last Paid (Ksh)", 300f, 120f, paint)
        canvas.drawText("Status", 420f, 120f, paint)

        // 🔹 Past Tenants Data
        paint.typeface = Typeface.DEFAULT
        paint.textSize = 10f
        paint.color = Color.BLACK

        val pastTenants = listOf(
            listOf("John Kamau", "2022-03-10", "2024-02-15", "15,000", "Cleared"),
            listOf("Jane Mwangi", "2021-07-05", "2023-10-30", "18,000", "Pending"),
            listOf("David Ouma", "2020-11-15", "2022-12-10", "14,500", "Cleared"),
            listOf("Alice Njoroge", "2019-09-01", "2021-08-20", "16,000", "Pending"),
            listOf("Michael Otieno", "2021-01-25", "2023-06-05", "17,500", "Cleared")
        )

        var y = 150f
        for (row in pastTenants) {
            canvas.drawText(row[0], 40f, y, paint)  // Name
            canvas.drawText(row[1], 140f, y, paint) // Move-in Date
            canvas.drawText(row[2], 220f, y, paint) // Move-out Date
            canvas.drawText(row[3], 320f, y, paint) // Last Paid Amount
            canvas.drawText(row[4], 420f, y, paint) // Status
            y += 25f
        }

        // 🔹 Footer
        paint.textSize = 10f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
        paint.color = Color.DKGRAY
        canvas.drawText("Generated by MaliApp", 180f, y + 40f, paint)

        pdfDocument.finishPage(page)

        // 🔹 Save the PDF
        val file = File(filePath)
        pdfDocument.writeTo(FileOutputStream(file))
        pdfDocument.close()
    }
}
