package com.joses.mali

import android.graphics.*
import android.graphics.pdf.PdfDocument
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

class PdfApartmentGeneratorImpl {
    fun generatePdf(filePath: String) {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(450, 700, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas
        val paint = Paint()

        // 🔹 Title (Bold & Centered)
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textSize = 18f
        paint.color = Color.BLACK
        canvas.drawText("Apartment Payment History", 80f, 40f, paint)

        // 🔹 Subtitle (Date - Centered)
        paint.textSize = 12f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
        val currentDate = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())
        canvas.drawText("Generated on: $currentDate", 100f, 70f, paint)

        // 🔹 Table Headers (Gray Background)
        paint.color = Color.LTGRAY
        canvas.drawRect(40f, 100f, 410f, 130f, paint)

        // 🔹 Table Headers - Text
        paint.color = Color.BLACK
        paint.textSize = 12f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)

        canvas.drawText("ID", 50f, 120f, paint)
        canvas.drawText("Tenant", 90f, 120f, paint)
        canvas.drawText("Amount (KSH)", 170f, 120f, paint)
        canvas.drawText("Status", 270f, 120f, paint)
        canvas.drawText("Mpesa Ref", 340f, 120f, paint)

        // 🔹 Table Rows - Dummy Data with Mpesa Shortcode
        paint.textSize = 11f
        paint.typeface = Typeface.DEFAULT
        paint.color = Color.BLACK

        val payments = listOf(
            listOf("001", "John Doe", "15,000", "Paid", "OCD2K5KI4C"),
            listOf("002", "Jane Smith", "18,000", "Pending", "XYZ1A2B3C4"),
            listOf("003", "David Kim", "12,000", "Paid", "LMN9X8Y7Z6"),
            listOf("004", "Alice Brown", "20,000", "Overdue", "PQR5T6U7V8"),
            listOf("005", "Brian Ouko", "17,500", "Paid", "ABC1D2E3F4")
        )

        var y = 150f
        for (row in payments) {
            canvas.drawText(row[0], 50f, y, paint)   // ID
            canvas.drawText(row[1], 90f, y, paint)   // Tenant Name
            canvas.drawText(row[2], 170f, y, paint)  // Amount
            canvas.drawText(row[3], 270f, y, paint)  // Status
            canvas.drawText(row[4], 340f, y, paint)  // Mpesa Ref
            y += 30f
        }

        // 🔹 Footer
        paint.textSize = 10f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
        paint.color = Color.DKGRAY
        canvas.drawText("Generated by Rent Management App", 100f, y + 40f, paint)

        pdfDocument.finishPage(page)

        // 🔹 Save the PDF
        val file = File(filePath)
        pdfDocument.writeTo(FileOutputStream(file))
        pdfDocument.close()
    }
}
