package com.joses.mali

import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import java.io.File
import java.io.FileOutputStream
import android.graphics.Color
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

//class PdfGeneratorImpl : PdfGenerator {
//     override fun generatePdf(reportData: String, filePath: String) {
//        val pdfDocument = PdfDocument()
//        val pageInfo = PdfDocument.PageInfo.Builder(400, 600, 1).create()
//        val page = pdfDocument.startPage(pageInfo)
//        val canvas: Canvas = page.canvas
//        val paint = Paint()
//
//        // 🔹 Title
//        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
//        paint.textSize = 18f
//        canvas.drawText("Payment Report", 100f, 40f, paint)
//
//        // 🔹 Subtitle (Date)
//        paint.textSize = 12f
//        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
//        canvas.drawText("Date: ${java.util.Date()}", 100f, 70f, paint)
//
//        paint.typeface = Typeface.DEFAULT // Reset Typeface
//        canvas.drawText("-------------------------------------------------", 50f, 90f, paint)
//
//        // 🔹 Table Headers
//        paint.textSize = 14f
//        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
//        canvas.drawText("ID", 50f, 120f, paint)
//        canvas.drawText("Name", 100f, 120f, paint)
//        canvas.drawText("Amount", 200f, 120f, paint)
//        canvas.drawText("Status", 280f, 120f, paint)
//
//        paint.typeface = Typeface.DEFAULT // Reset
//        canvas.drawText("-------------------------------------------------", 50f, 130f, paint)
//
//        // 🔹 Dummy Payment Data
//        val payments = listOf(
//           listOf("001", "John Doe", "$500", "Paid"),
//           listOf("002", "Jane Smith", "$750", "Pending"),
//           listOf("003", "Michael J.", "$600", "Paid"),
//           listOf("004", "Emily Davis", "$400", "Overdue")
//        )
//
//        var y = 150f
//        for (row in payments) {
//           canvas.drawText(row[0], 50f, y, paint)
//           canvas.drawText(row[1], 100f, y, paint)
//           canvas.drawText(row[2], 200f, y, paint)
//           canvas.drawText(row[3], 280f, y, paint)
//           y += 30f
//        }
//
//        // 🔹 Footer
//        paint.textSize = 10f
//        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
//        canvas.drawText("Generated by MyApp", 100f, y + 40f, paint)
//
//        pdfDocument.finishPage(page)
//
//        // 🔹 Save the PDF File
//        val file = File(filePath)
//        pdfDocument.writeTo(FileOutputStream(file))
//        pdfDocument.close()
//     }
//}



class PdfGeneratorImpl {
   fun generatePdf(filePath: String) {
      val pdfDocument = PdfDocument()
      val pageInfo = PdfDocument.PageInfo.Builder(400, 700, 1).create()
      val page = pdfDocument.startPage(pageInfo)
      val canvas: Canvas = page.canvas
      val paint = Paint()

      // 🔹 Title
      paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
      paint.textSize = 18f
      paint.color = Color.BLACK
      canvas.drawText("John Kamau - Payment History", 50f, 40f, paint)

      // 🔹 Subtitle (Current Date)
      paint.textSize = 12f
      paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
      val currentDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date())
      canvas.drawText("Generated on: $currentDate", 50f, 70f, paint)

      // 🔹 Table Headers Background
      paint.color = Color.LTGRAY
      canvas.drawRect(30f, 100f, 370f, 130f, paint)

      // 🔹 Table Headers
      paint.color = Color.BLACK
      paint.textSize = 12f
      paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
      canvas.drawText("Date", 40f, 120f, paint)
      canvas.drawText("Amount (Ksh)", 110f, 120f, paint)
      canvas.drawText("Status", 220f, 120f, paint)
      canvas.drawText("Mpesa Ref", 290f, 120f, paint)

      // 🔹 Payment History (Past 8 Months)
      paint.typeface = Typeface.DEFAULT
      paint.textSize = 10f
      paint.color = Color.BLACK

      val payments = listOf(
         listOf("2024-08-05", "15,000", "Paid", "OCD2K5KI4C"),
         listOf("2024-09-05", "15,000", "Paid", "LJ56TYU4K8"),
         listOf("2024-10-05", "15,000", "Paid", "QW8ZTY76MN"),
         listOf("2024-11-05", "15,000", "Paid", "MN76D5LJ45"),
         listOf("2024-12-05", "15,000", "Paid", "ZX78LOP6RT"),
         listOf("2025-01-05", "15,000", "Paid", "YT56NM8VCR"),
         listOf("2025-02-05", "15,000", "Paid", "UI9OP67TYL"),
         listOf("2025-03-05", "15,000", "Paid", "XC45PL98TY")
      )

      var y = 150f
      for (row in payments) {
         canvas.drawText(row[0], 40f, y, paint)  // Date
         canvas.drawText(row[1], 120f, y, paint) // Amount
         canvas.drawText(row[2], 220f, y, paint) // Status
         canvas.drawText(row[3], 290f, y, paint) // Mpesa Ref
         y += 25f
      }

      // 🔹 Footer
      paint.textSize = 10f
      paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
      paint.color = Color.DKGRAY
      canvas.drawText("Generated by MaliApp", 130f, y + 40f, paint)

      pdfDocument.finishPage(page)

      // 🔹 Save the PDF
      val file = File(filePath)
      pdfDocument.writeTo(FileOutputStream(file))
      pdfDocument.close()
   }
}

